#!/usr/bin/env bun

import assert from 'node:assert/strict'
import {
  buildGeminiFunctionDeclaration,
  normalizeGeminiToolParameterSchema,
  validateGeminiFunctionName,
} from '../source/src/services/api/geminiToolSchema.js'
import { collectGeminiContents } from '../source/src/services/api/geminiContent.js'

const todoSchema = normalizeGeminiToolParameterSchema({
  type: 'object',
  strict: true,
  additionalProperties: false,
  properties: {
    todos: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          content: { type: 'string' },
          status: {
            anyOf: [
              { const: 'pending' },
              { const: 'in_progress' },
              { const: 'completed' },
            ],
          },
        },
        required: ['content', 'status'],
      },
    },
  },
  required: ['todos'],
})
assert.equal(todoSchema.type, 'object')
assert.equal('strict' in todoSchema, false)
assert.equal('additionalProperties' in todoSchema, false)
assert.deepEqual(
  (((todoSchema.properties as never).todos as never).items as never).properties
    .status.enum,
  ['pending', 'in_progress', 'completed'],
)

const bashDeclaration = buildGeminiFunctionDeclaration({
  name: 'Bash',
  description: 'Runs a shell command.',
  parameters: {
    type: 'object',
    properties: {
      command: { type: 'string' },
      timeout: { type: ['integer', 'null'] },
    },
    required: ['command'],
  },
})
assert.equal(bashDeclaration.name, 'Bash')
assert.equal(
  ((bashDeclaration.parameters as never).properties.timeout as never).nullable,
  true,
)

const mcpSchema = normalizeGeminiToolParameterSchema({
  type: 'object',
  properties: {},
  additionalProperties: true,
})
assert.deepEqual(mcpSchema, { type: 'object', properties: {} })

const boundedIntegerSchema = normalizeGeminiToolParameterSchema({
  type: 'object',
  properties: {
    limit: {
      type: 'integer',
      minimum: 1,
      exclusiveMinimum: 0,
      maximum: 10,
      exclusiveMaximum: 11,
    },
    choice: {
      oneOf: [
        { type: 'string', enum: ['a'] },
        { type: 'string', enum: ['b'] },
      ],
    },
  },
  required: ['limit'],
})
assert.equal(
  'exclusiveMinimum' in ((boundedIntegerSchema.properties as never).limit as never),
  false,
)
assert.equal(
  'exclusiveMaximum' in ((boundedIntegerSchema.properties as never).limit as never),
  false,
)
assert.deepEqual(
  ((boundedIntegerSchema.properties as never).choice as never).enum,
  ['a', 'b'],
)

assert.equal(validateGeminiFunctionName('mcp__server__tool'), null)
assert.match(validateGeminiFunctionName('bad-tool') ?? '', /invalid/)

const replay = collectGeminiContents({
  messages: [
    {
      type: 'assistant',
      message: {
        content: [
          {
            type: 'tool_use',
            id: 'call_image',
            name: 'ReadImage',
            input: { path: 'image.png' },
            providerMetadata: {
              gemini: {
                thoughtSignature: 'sig-image',
                functionName: 'ReadImage',
                requiresThoughtSignature: true,
              },
            },
          },
        ],
      },
    },
    {
      type: 'user',
      message: {
        content: [
          {
            type: 'tool_result',
            tool_use_id: 'call_image',
            content: [
              {
                type: 'image',
                source: {
                  type: 'base64',
                  media_type: 'image/png',
                  data: 'aW1hZ2U=',
                },
              },
            ],
          },
        ],
      },
    },
  ] as never,
})
assert.equal(replay.validationError, undefined)
assert.equal(replay.contents[0]?.parts[0]?.thoughtSignature, 'sig-image')
assert.equal(
  replay.contents[1]?.parts[0]?.functionResponse?.name,
  'ReadImage',
)
assert.match(
  replay.contents[1]?.parts[0]?.functionResponse?.response.content as string,
  /image\/png/,
)

const largeResult = collectGeminiContents({
  messages: [
    {
      type: 'assistant',
      message: {
        content: [
          {
            type: 'tool_use',
            id: 'call_large',
            name: 'LargeJson',
            input: {},
          },
        ],
      },
    },
    {
      type: 'user',
      message: {
        content: [
          {
            type: 'tool_result',
            tool_use_id: 'call_large',
            content: [{ type: 'text', text: 'x'.repeat(200_000) }],
          },
        ],
      },
    },
  ] as never,
})
assert.equal(
  String(largeResult.contents[1]?.parts[0]?.functionResponse?.response.content)
    .length,
  200_000,
)

console.log('gemini-tool-schema self-test passed')

// Simulate the SendMessageTool schema generated by zodToJsonSchema
const sendMessageSchema = {
  type: "object",
  properties: {
    message: {
      anyOf: [
        { type: "string" },
        {
          anyOf: [
            {
              type: "object",
              properties: {
                type: { type: "string", const: "shutdown_request" }
              }
            },
            {
              type: "object",
              properties: {
                type: { type: "string", const: "shutdown_response" }
              }
            }
          ]
        }
      ]
    }
  }
};

const normalizedSendMessage = normalizeGeminiToolParameterSchema(sendMessageSchema);
assert.equal(Array.isArray((normalizedSendMessage.properties as any).message.anyOf), true, "anyOf is preserved at top level");
assert.equal(Array.isArray((normalizedSendMessage.properties as any).message.anyOf[1].anyOf), true, "anyOf is preserved at nested level");
assert.deepEqual((normalizedSendMessage.properties as any).message.anyOf[1].anyOf[0].properties.type.enum, ["shutdown_request"], "const is converted to enum");

// Simulate AgentTool schema
const agentToolSchema = {
  type: "object",
  properties: {
    isolation: {
      type: "string",
      enum: ["worktree"]
    }
  }
};

const normalizedAgent = normalizeGeminiToolParameterSchema(agentToolSchema);
assert.deepEqual((normalizedAgent.properties as any).isolation.enum, ["worktree"], "enum is preserved");

// Simulate TaskUpdateTool schema
const taskUpdateSchema = {
  type: "object",
  properties: {
    status: {
      anyOf: [
        {
          type: "string",
          enum: ["pending", "in_progress", "completed"]
        },
        {
          type: "string",
          enum: ["deleted"]
        }
      ]
    }
  }
};

const normalizedTaskUpdate = normalizeGeminiToolParameterSchema(taskUpdateSchema);
assert.equal((normalizedTaskUpdate.properties as any).status.anyOf, undefined, "anyOf is collapsed");
assert.deepEqual((normalizedTaskUpdate.properties as any).status.enum, ["pending", "in_progress", "completed", "deleted"], "enums are merged");

console.log('Gemini swarm schema normalization self-tests passed');
